name: Lighthouse Check
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install, build
        run: |
          npm install
          npm run build
          npm run serve
      - name: Run lighthouse
        run: |
          npm i -g lighthouse
          lighthouse \
            --chrome-flags="--headless" \
            --output html --output-path ./report.html \
            'http://localhost:9000/'
      - name: Upload result
        uses: actions/upload-artifact@master
        with:
          name: report
          path: report.html