name: Build project and Run Lighthouse CI
on: [pull_request]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install, build
        run: |
          npm install
          npm run build
      - name: run Lighthouse CI
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          npm install -g @lhci/cli@0.3.x
          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
      - name: 成果物作ってんよ
        run: |
          mkdir -p path/to/artifact
          echo hello > path/to/artifact/world.txt
      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: path/to/artifact
